# ==========================================
# 13_infra_providers.ps1
# CREACIÓN DE ADAPTADORES DE PROVEEDORES Y FACTORY
# ==========================================
$basePath = "C:\source\test\code\Nueva carpeta\Tumipay\java-projects\tumipay-payin-service"

Write-Host "Creando Provider Adapters y Factory en: $basePath" -ForegroundColor Cyan

function Write-InfraFile {
    param ([string]$relativePath, [string]$content)
    $fullPath = Join-Path -Path $basePath -ChildPath $relativePath
    $parentDir = Split-Path -Parent $fullPath
    if (-not (Test-Path $parentDir)) { New-Item -ItemType Directory -Force -Path $parentDir | Out-Null }
    $content | Out-File -FilePath $fullPath -Encoding UTF8 -Force
    Write-Host "✅ Archivo creado: $relativePath" -ForegroundColor Green
}

# ==========================================
# 1. ADAPTADORES ESPECÍFICOS (Mocks)
# ==========================================

# 1.1 PayUAdapter.java
Write-InfraFile "src\main\java\com\tumi\payln\infrastructure\adapter\provider\PayUAdapter.java" 'package com.tumi.payln.infrastructure.adapter.provider;

import com.tumi.payln.application.port.IPaymentProviderPort;
import com.tumi.payln.domain.model.Amount;
import com.tumi.payln.domain.model.ProviderId;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;
import java.util.UUID;

@Slf4j
@Component
public class PayUAdapter implements IPaymentProviderPort {
    
    @Override
    public PaymentResult processPayment(ProviderId providerId, Amount amount, PaymentRequest request) {
        log.info("--> [PayU] Processing payment: client={}, amount={} COP", request.clientId(), amount.value());
        
        // Simulación
        try {
            Thread.sleep(100); 
            boolean success = true; // Forzamos éxito para la demo, o usa Math.random() > 0.1
            
            if (success) {
                String ref = "payu-" + UUID.randomUUID().toString().substring(0, 8);
                return new PaymentResult(true, ref, "Approved by PayU");
            } else {
                return new PaymentResult(false, null, "Declined by PayU");
            }
        } catch (Exception e) {
            return new PaymentResult(false, null, "PayU Error: " + e.getMessage());
        }
    }
}'

# 1.2 KushkiAdapter.java
Write-InfraFile "src\main\java\com\tumi\payln\infrastructure\adapter\provider\KushkiAdapter.java" 'package com.tumi.payln.infrastructure.adapter.provider;

import com.tumi.payln.application.port.IPaymentProviderPort;
import com.tumi.payln.domain.model.Amount;
import com.tumi.payln.domain.model.ProviderId;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;
import java.util.UUID;

@Slf4j
@Component
public class KushkiAdapter implements IPaymentProviderPort {
    
    @Override
    public PaymentResult processPayment(ProviderId providerId, Amount amount, PaymentRequest request) {
        log.info("--> [Kushki] Processing payment: client={}, amount={} COP", request.clientId(), amount.value());
        
        try {
            Thread.sleep(150);
            String ref = "kushki-" + UUID.randomUUID().toString().substring(0, 10);
            return new PaymentResult(true, ref, "Ticket generated by Kushki");
        } catch (Exception e) {
            return new PaymentResult(false, null, "Kushki Error: " + e.getMessage());
        }
    }
}'

# 1.3 StripeAdapter.java
Write-InfraFile "src\main\java\com\tumi\payln\infrastructure\adapter\provider\StripeAdapter.java" 'package com.tumi.payln.infrastructure.adapter.provider;

import com.tumi.payln.application.port.IPaymentProviderPort;
import com.tumi.payln.domain.model.Amount;
import com.tumi.payln.domain.model.ProviderId;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;
import java.util.UUID;

@Slf4j
@Component
public class StripeAdapter implements IPaymentProviderPort {
    
    @Override
    public PaymentResult processPayment(ProviderId providerId, Amount amount, PaymentRequest request) {
        log.info("--> [Stripe] Processing payment: client={}, amount={} (Converted to USD)", request.clientId(), amount.value());
        
        try {
            Thread.sleep(80);
            String ref = "ch_" + UUID.randomUUID().toString().replace("-", "");
            return new PaymentResult(true, ref, "Succeeded via Stripe");
        } catch (Exception e) {
            return new PaymentResult(false, null, "Stripe Error: " + e.getMessage());
        }
    }
}'

# ==========================================
# 2. FACTORY
# ==========================================

# 2.1 PaymentProviderFactory.java
Write-InfraFile "src\main\java\com\tumi\payln\infrastructure\adapter\factory\PaymentProviderFactory.java" 'package com.tumi.payln.infrastructure.adapter.factory;

import com.tumi.payln.application.port.IPaymentProviderPort;
import com.tumi.payln.domain.model.ProviderId;
import com.tumi.payln.infrastructure.adapter.provider.*;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

@Component
@RequiredArgsConstructor
public class PaymentProviderFactory {
    
    private final PayUAdapter payUAdapter;
    private final KushkiAdapter kushkiAdapter;
    private final StripeAdapter stripeAdapter;
    
    public IPaymentProviderPort getProvider(ProviderId providerId) {
        return switch (providerId.value()) {
            case "payu" -> payUAdapter;
            case "kushki" -> kushkiAdapter;
            case "stripe" -> stripeAdapter;
            default -> throw new IllegalArgumentException("Unsupported provider: " + providerId.value());
        };
    }
}'

# ==========================================
# 3. ADAPTADOR PRINCIPAL (WRAPPER)
# ==========================================

# 3.1 PaymentProviderAdapter.java
# NOTA: Se mueve a adapter/provider para coherencia lógica, aunque implementa el puerto.
# Se usa @Primary para que Spring sepa que este es el principal a inyectar en el Caso de Uso.
Write-InfraFile "src\main\java\com\tumi\payln\infrastructure\adapter\provider\PaymentProviderAdapter.java" 'package com.tumi.payln.infrastructure.adapter.provider;

import com.tumi.payln.application.port.IPaymentProviderPort;
import com.tumi.payln.domain.model.Amount;
import com.tumi.payln.domain.model.ProviderId;
import com.tumi.payln.infrastructure.adapter.factory.PaymentProviderFactory;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.annotation.Primary;
import org.springframework.stereotype.Component;

@Slf4j
@Primary 
@Component
@RequiredArgsConstructor
public class PaymentProviderAdapter implements IPaymentProviderPort {
    
    private final PaymentProviderFactory paymentProviderFactory;
    
    @Override
    public PaymentResult processPayment(ProviderId providerId, Amount amount, PaymentRequest request) {
        log.debug("Routing payment to provider: {}", providerId.value());
        
        IPaymentProviderPort provider = paymentProviderFactory.getProvider(providerId);
        return provider.processPayment(providerId, amount, request);
    }
}'

Write-Host "✅ Providers y Factory generados correctamente." -ForegroundColor Green