package com.tumi.payln.infrastructure.adapter.provider;

import com.tumi.payln.application.port.IPaymentProviderPort;
import com.tumi.payln.domain.model.Amount;
import com.tumi.payln.domain.model.ProviderId;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;
import java.util.UUID;

@Slf4j
@Component
public class KushkiAdapter implements IPaymentProviderPort {
    
    @Override
    public PaymentResult processPayment(ProviderId providerId, Amount amount, PaymentRequest request) {
        log.info("--> [Kushki] Processing payment: client={}, amount={} COP", request.clientId(), amount.value());
        
        try {
            Thread.sleep(150);
            String ref = "kushki-" + UUID.randomUUID().toString().substring(0, 10);
            return new PaymentResult(true, ref, "Ticket generated by Kushki");
        } catch (Exception e) {
            return new PaymentResult(false, null, "Kushki Error: " + e.getMessage());
        }
    }
}
